-- -------------------------------------------------------------
-- 
-- File Name: /u/home/eraguzin/matlab/LNspec/matlab/codegen/cal_average_instance_C1/hdlsrc/cal_average_instance_C1_fixpt.vhd
-- Created: 2024-01-11 11:00:16
-- 
-- Generated by MATLAB 9.12, MATLAB Coder 5.4 and HDL Coder 3.20
-- 
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Design base rate: 1
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        1
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- outreal                       ce_out        1
-- outimag                       ce_out        1
-- powertop                      ce_out        1
-- powerbot                      ce_out        1
-- drift_FD                      ce_out        1
-- drift_SD                      ce_out        1
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: cal_average_instance_C1_fixpt
-- Source Path: cal_average_instance_C1_fixpt
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.cal_average_instance_C1_fixpt_pkg.ALL;

ENTITY cal_average_instance_C1_fixpt IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        real_in                           :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En30
        imag_in                           :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En30
        calbin                            :   IN    std_logic_vector(9 DOWNTO 0);  -- ufix10
        phase_cor_re                      :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En30
        phase_cor_im                      :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En30
        kar                               :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
        tick                              :   IN    std_logic_vector(1 DOWNTO 0);  -- sfix2
        readyout                          :   IN    std_logic;
        readycal                          :   IN    std_logic;
        ce_out                            :   OUT   std_logic;
        outreal                           :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En24
        outimag                           :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En24
        powertop                          :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32_En18
        powerbot                          :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32_En30
        drift_FD                          :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En4
        drift_SD                          :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_E11
        );
END cal_average_instance_C1_fixpt;


ARCHITECTURE rtl OF cal_average_instance_C1_fixpt IS

  -- Functions
  -- HDL_SIM_INDEX_CHECK: Enabled by the "SimIndexCheck" option.
  FUNCTION hdl_sim_index_check(addr : integer; low: integer; high: integer ) RETURN integer IS
  BEGIN
    --pragma translate off
    IF addr >= low AND addr <= high THEN
      RETURN addr;
    ELSE
      -- Index out of bounds. Undefined result. Return arbitrary value in range.
      RETURN low;
    END IF;
    --pragma translate on
    return addr;
  END FUNCTION;


  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL outreal_1                        : signed(31 DOWNTO 0);  -- sfix32_En24
  SIGNAL tmp                              : signed(31 DOWNTO 0);  -- sfix32_En24
  SIGNAL tmp_re                           : vector_of_signed32(0 TO 262143);  -- sfix32_En24 [262144]
  SIGNAL tmp_im                           : vector_of_signed32(0 TO 262143);  -- sfix32_En24 [262144]
  SIGNAL tmp_re_1                         : signed(31 DOWNTO 0);  -- sfix32_En24
  SIGNAL tmp_im_1                         : signed(31 DOWNTO 0);  -- sfix32_En24
  SIGNAL calbin_unsigned                  : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL tmp_1                            : signed(31 DOWNTO 0);  -- int32
  SIGNAL p166tmp_sub_cast                 : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_re_2                         : signed(31 DOWNTO 0);  -- sfix32_En24
  SIGNAL tmp_im_2                         : signed(31 DOWNTO 0);  -- sfix32_En24
  SIGNAL real_in_signed                   : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL imag_in_signed                   : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL cplx_in_re                       : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL cplx_in_im                       : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL ar                               : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL phase_cor_re_signed              : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL phase_cor_im_signed              : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL br                               : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL ai                               : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL bi                               : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL tmp_re_3                         : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL tmp_im_3                         : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL p135tmp_mul_temp                 : signed(63 DOWNTO 0);  -- sfix64_En60
  SIGNAL p135tmp_sub_cast                 : signed(64 DOWNTO 0);  -- sfix65_En60
  SIGNAL p135tmp_mul_temp_1               : signed(63 DOWNTO 0);  -- sfix64_En60
  SIGNAL p135tmp_sub_cast_1               : signed(64 DOWNTO 0);  -- sfix65_En60
  SIGNAL p135tmp_sub_temp                 : signed(64 DOWNTO 0);  -- sfix65_En60
  SIGNAL p135tmp_mul_temp_2               : signed(63 DOWNTO 0);  -- sfix64_En60
  SIGNAL p135tmp_add_cast                 : signed(64 DOWNTO 0);  -- sfix65_En60
  SIGNAL p135tmp_mul_temp_3               : signed(63 DOWNTO 0);  -- sfix64_En60
  SIGNAL p135tmp_add_cast_1               : signed(64 DOWNTO 0);  -- sfix65_En60
  SIGNAL p135tmp_add_temp                 : signed(64 DOWNTO 0);  -- sfix65_En60
  SIGNAL tmp_re_4                         : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL tmp_im_4                         : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL tmp_2                            : signed(31 DOWNTO 0);  -- int32
  SIGNAL p152tmp_sub_cast                 : signed(31 DOWNTO 0);  -- int32
  SIGNAL sum0_re                          : vector_of_signed32(0 TO 262143);  -- sfix32_En24 [262144]
  SIGNAL sum0_im                          : vector_of_signed32(0 TO 262143);  -- sfix32_En24 [262144]
  SIGNAL tmp_re_5                         : signed(31 DOWNTO 0);  -- sfix32_En24
  SIGNAL tmp_im_5                         : signed(31 DOWNTO 0);  -- sfix32_En24
  SIGNAL p151tmp_sub_cast                 : signed(31 DOWNTO 0);  -- int32
  SIGNAL p151tmp_sub_cast_1               : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_re_6                         : signed(31 DOWNTO 0);  -- sfix32_En24
  SIGNAL tmp_im_6                         : signed(31 DOWNTO 0);  -- sfix32_En24
  SIGNAL tmp_re_7                         : signed(31 DOWNTO 0);  -- sfix32_En24
  SIGNAL tmp_im_7                         : signed(31 DOWNTO 0);  -- sfix32_En24
  SIGNAL p114tmp_add_cast                 : signed(38 DOWNTO 0);  -- sfix39_En30
  SIGNAL p114tmp_add_cast_1               : signed(38 DOWNTO 0);  -- sfix39_En30
  SIGNAL p114tmp_add_temp                 : signed(38 DOWNTO 0);  -- sfix39_En30
  SIGNAL p114tmp_add_cast_2               : signed(38 DOWNTO 0);  -- sfix39_En30
  SIGNAL p114tmp_add_cast_3               : signed(38 DOWNTO 0);  -- sfix39_En30
  SIGNAL p114tmp_add_temp_1               : signed(38 DOWNTO 0);  -- sfix39_En30
  SIGNAL sum0_re_1                        : vector_of_signed32(0 TO 262143);  -- sfix32_En24 [262144]
  SIGNAL sum0_im_1                        : vector_of_signed32(0 TO 262143);  -- sfix32_En24 [262144]
  SIGNAL tmp_re_8                         : vector_of_signed32(0 TO 262143);  -- sfix32_En24 [262144]
  SIGNAL tmp_im_8                         : vector_of_signed32(0 TO 262143);  -- sfix32_En24 [262144]
  SIGNAL sum0_re_2                        : vector_of_signed32(0 TO 262143);  -- sfix32_En24 [262144]
  SIGNAL sum0_im_2                        : vector_of_signed32(0 TO 262143);  -- sfix32_En24 [262144]
  SIGNAL tmp_re_9                         : vector_of_signed32(0 TO 262143);  -- sfix32_En24 [262144]
  SIGNAL tmp_im_9                         : vector_of_signed32(0 TO 262143);  -- sfix32_En24 [262144]
  SIGNAL tmp_re_10                        : vector_of_signed32(0 TO 262143);  -- sfix32_En24 [262144]
  SIGNAL tmp_im_10                        : vector_of_signed32(0 TO 262143);  -- sfix32_En24 [262144]
  SIGNAL tmp_re_11                        : vector_of_signed32(0 TO 262143);  -- sfix32_En24 [262144]
  SIGNAL tmp_im_11                        : vector_of_signed32(0 TO 262143);  -- sfix32_En24 [262144]
  SIGNAL csum0_re                         : signed(31 DOWNTO 0);  -- sfix32_En24
  SIGNAL csum0_im                         : signed(31 DOWNTO 0);  -- sfix32_En24
  SIGNAL p111csum0_sub_cast               : signed(31 DOWNTO 0);  -- int32
  SIGNAL p111csum0_sub_cast_1             : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_3                            : signed(31 DOWNTO 0);  -- sfix32_En24
  SIGNAL tmp_4                            : signed(31 DOWNTO 0);  -- sfix32_En24
  SIGNAL tmp_5                            : signed(31 DOWNTO 0);  -- sfix32_En24
  SIGNAL tmp_6                            : signed(31 DOWNTO 0);  -- sfix32_En24
  SIGNAL outimag_1                        : signed(31 DOWNTO 0);  -- sfix32_En24
  SIGNAL tmp_7                            : signed(31 DOWNTO 0);  -- sfix32_En24
  SIGNAL tmp_8                            : signed(31 DOWNTO 0);  -- sfix32_En24
  SIGNAL tmp_9                            : signed(31 DOWNTO 0);  -- sfix32_En24
  SIGNAL tmp_10                           : signed(31 DOWNTO 0);  -- sfix32_En24
  SIGNAL tmp_11                           : signed(31 DOWNTO 0);  -- sfix32_En24
  SIGNAL powertop_1                       : unsigned(31 DOWNTO 0);  -- ufix32_En18
  SIGNAL tmp_12                           : unsigned(31 DOWNTO 0);  -- ufix32_En18
  SIGNAL ar_1                             : signed(31 DOWNTO 0);  -- sfix32_En24
  SIGNAL y_re                             : signed(31 DOWNTO 0);  -- sfix32_En24
  SIGNAL y_im                             : signed(31 DOWNTO 0);  -- sfix32_En24
  SIGNAL p108y_cast                       : signed(32 DOWNTO 0);  -- sfix33_En24
  SIGNAL p108y_cast_1                     : signed(32 DOWNTO 0);  -- sfix33_En24
  SIGNAL br_1                             : signed(31 DOWNTO 0);  -- sfix32_En24
  SIGNAL ai_1                             : signed(31 DOWNTO 0);  -- sfix32_En24
  SIGNAL bi_1                             : signed(31 DOWNTO 0);  -- sfix32_En24
  SIGNAL tmp_13                           : unsigned(31 DOWNTO 0);  -- ufix32_En18
  SIGNAL p105tmp_mul_temp                 : signed(63 DOWNTO 0);  -- sfix64_En48
  SIGNAL p105tmp_sub_cast                 : signed(64 DOWNTO 0);  -- sfix65_En48
  SIGNAL p105tmp_mul_temp_1               : signed(63 DOWNTO 0);  -- sfix64_En48
  SIGNAL p105tmp_sub_cast_1               : signed(64 DOWNTO 0);  -- sfix65_En48
  SIGNAL p105tmp_sub_temp                 : signed(64 DOWNTO 0);  -- sfix65_En48
  SIGNAL tmp_14                           : unsigned(31 DOWNTO 0);  -- ufix32_En18
  SIGNAL tmp_15                           : unsigned(31 DOWNTO 0);  -- ufix32_En18
  SIGNAL tmp_16                           : unsigned(31 DOWNTO 0);  -- ufix32_En18
  SIGNAL powerbot_1                       : unsigned(31 DOWNTO 0);  -- ufix32_En30
  SIGNAL tmp_17                           : unsigned(31 DOWNTO 0);  -- ufix32_En30
  SIGNAL tmp_re_12                        : vector_of_signed32(0 TO 262143);  -- sfix32_En30 [262144]
  SIGNAL tmp_im_12                        : vector_of_signed32(0 TO 262143);  -- sfix32_En30 [262144]
  SIGNAL tmp_re_13                        : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL tmp_im_13                        : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL tmp_18                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL p168tmp_sub_cast                 : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_re_14                        : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL tmp_im_14                        : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL cr                               : signed(33 DOWNTO 0);  -- sfix34_En30
  SIGNAL tick_signed                      : signed(1 DOWNTO 0);  -- sfix2
  SIGNAL tmp_19                           : signed(33 DOWNTO 0);  -- sfix34_En30
  SIGNAL tmp_20                           : signed(33 DOWNTO 0);  -- sfix34_En30
  SIGNAL ci                               : signed(33 DOWNTO 0);  -- sfix34_En30
  SIGNAL tmp_21                           : signed(33 DOWNTO 0);  -- sfix34_En30
  SIGNAL tmp_22                           : signed(33 DOWNTO 0);  -- sfix34_En30
  SIGNAL tmp_23                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL p154tmp_sub_cast                 : signed(31 DOWNTO 0);  -- int32
  SIGNAL sum0alt_re                       : vector_of_signed32(0 TO 262143);  -- sfix32_En30 [262144]
  SIGNAL sum0alt_im                       : vector_of_signed32(0 TO 262143);  -- sfix32_En30 [262144]
  SIGNAL tmp_re_15                        : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL tmp_im_15                        : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL p153tmp_sub_cast                 : signed(31 DOWNTO 0);  -- int32
  SIGNAL p153tmp_sub_cast_1               : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_re_16                        : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL tmp_im_16                        : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL tmp_re_17                        : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL tmp_im_17                        : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL p90tmp_add_cast                  : signed(34 DOWNTO 0);  -- sfix35_En30
  SIGNAL p90tmp_add_cast_1                : signed(34 DOWNTO 0);  -- sfix35_En30
  SIGNAL p90tmp_add_temp                  : signed(34 DOWNTO 0);  -- sfix35_En30
  SIGNAL p90tmp_add_cast_2                : signed(34 DOWNTO 0);  -- sfix35_En30
  SIGNAL p90tmp_add_cast_3                : signed(34 DOWNTO 0);  -- sfix35_En30
  SIGNAL p90tmp_add_temp_1                : signed(34 DOWNTO 0);  -- sfix35_En30
  SIGNAL sum0alt_re_1                     : vector_of_signed32(0 TO 262143);  -- sfix32_En30 [262144]
  SIGNAL sum0alt_im_1                     : vector_of_signed32(0 TO 262143);  -- sfix32_En30 [262144]
  SIGNAL tmp_re_18                        : vector_of_signed32(0 TO 262143);  -- sfix32_En30 [262144]
  SIGNAL tmp_im_18                        : vector_of_signed32(0 TO 262143);  -- sfix32_En30 [262144]
  SIGNAL sum0alt_re_2                     : vector_of_signed32(0 TO 262143);  -- sfix32_En30 [262144]
  SIGNAL sum0alt_im_2                     : vector_of_signed32(0 TO 262143);  -- sfix32_En30 [262144]
  SIGNAL tmp_re_19                        : vector_of_signed32(0 TO 262143);  -- sfix32_En30 [262144]
  SIGNAL tmp_im_19                        : vector_of_signed32(0 TO 262143);  -- sfix32_En30 [262144]
  SIGNAL tmp_re_20                        : vector_of_signed32(0 TO 262143);  -- sfix32_En30 [262144]
  SIGNAL tmp_im_20                        : vector_of_signed32(0 TO 262143);  -- sfix32_En30 [262144]
  SIGNAL tmp_re_21                        : vector_of_signed32(0 TO 262143);  -- sfix32_En30 [262144]
  SIGNAL tmp_im_21                        : vector_of_signed32(0 TO 262143);  -- sfix32_En30 [262144]
  SIGNAL csum0alt_re                      : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL csum0alt_im                      : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL p87csum0alt_sub_cast             : signed(31 DOWNTO 0);  -- int32
  SIGNAL p87csum0alt_sub_cast_1           : signed(31 DOWNTO 0);  -- int32
  SIGNAL ar_2                             : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL y_re_1                           : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL y_im_1                           : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL p84y_cast                        : signed(32 DOWNTO 0);  -- sfix33_En30
  SIGNAL p84y_cast_1                      : signed(32 DOWNTO 0);  -- sfix33_En30
  SIGNAL br_2                             : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL ai_2                             : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL bi_2                             : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL tmp_24                           : unsigned(31 DOWNTO 0);  -- ufix32_En30
  SIGNAL p81tmp_mul_temp                  : signed(63 DOWNTO 0);  -- sfix64_En60
  SIGNAL p81tmp_sub_cast                  : signed(64 DOWNTO 0);  -- sfix65_En60
  SIGNAL p81tmp_mul_temp_1                : signed(63 DOWNTO 0);  -- sfix64_En60
  SIGNAL p81tmp_sub_cast_1                : signed(64 DOWNTO 0);  -- sfix65_En60
  SIGNAL p81tmp_sub_temp                  : signed(64 DOWNTO 0);  -- sfix65_En60
  SIGNAL tmp_25                           : unsigned(31 DOWNTO 0);  -- ufix32_En30
  SIGNAL tmp_26                           : unsigned(31 DOWNTO 0);  -- ufix32_En30
  SIGNAL tmp_27                           : unsigned(31 DOWNTO 0);  -- ufix32_En30
  SIGNAL drift_FD_1                       : signed(31 DOWNTO 0);  -- sfix32_En4
  SIGNAL tmp_28                           : signed(31 DOWNTO 0);  -- sfix32_En4
  SIGNAL tmp_re_22                        : vector_of_signed32(0 TO 262143);  -- sfix32_En9 [262144]
  SIGNAL tmp_im_22                        : vector_of_signed32(0 TO 262143);  -- sfix32_En9 [262144]
  SIGNAL tmp_re_23                        : signed(31 DOWNTO 0);  -- sfix32_En9
  SIGNAL tmp_im_23                        : signed(31 DOWNTO 0);  -- sfix32_En9
  SIGNAL tmp_29                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL p170tmp_sub_cast                 : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_re_24                        : signed(31 DOWNTO 0);  -- sfix32_En9
  SIGNAL tmp_im_24                        : signed(31 DOWNTO 0);  -- sfix32_En9
  SIGNAL pre                              : signed(48 DOWNTO 0);  -- sfix49_En30
  SIGNAL ar_3                             : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL kar_unsigned                     : unsigned(15 DOWNTO 0);  -- ufix16
  SIGNAL c_re                             : unsigned(15 DOWNTO 0);  -- ufix16
  SIGNAL c_im                             : unsigned(15 DOWNTO 0);  -- ufix16
  SIGNAL br_3                             : unsigned(15 DOWNTO 0);  -- ufix16
  SIGNAL ai_3                             : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL bi_3                             : unsigned(15 DOWNTO 0);  -- ufix16
  SIGNAL tmp_30                           : signed(48 DOWNTO 0);  -- sfix49_En30
  SIGNAL p117tmp_cast                     : signed(16 DOWNTO 0);  -- sfix17
  SIGNAL p117tmp_mul_temp                 : signed(48 DOWNTO 0);  -- sfix49_En30
  SIGNAL p117tmp_sub_cast                 : signed(47 DOWNTO 0);  -- sfix48_En30
  SIGNAL p117tmp_sub_cast_1               : signed(48 DOWNTO 0);  -- sfix49_En30
  SIGNAL p117tmp_cast_1                   : signed(16 DOWNTO 0);  -- sfix17
  SIGNAL p117tmp_mul_temp_1               : signed(48 DOWNTO 0);  -- sfix49_En30
  SIGNAL p117tmp_sub_cast_2               : signed(47 DOWNTO 0);  -- sfix48_En30
  SIGNAL p117tmp_sub_cast_3               : signed(48 DOWNTO 0);  -- sfix49_En30
  SIGNAL tmp_31                           : signed(48 DOWNTO 0);  -- sfix49_En30
  SIGNAL pim                              : signed(48 DOWNTO 0);  -- sfix49_En30
  SIGNAL tmp_32                           : signed(48 DOWNTO 0);  -- sfix49_En30
  SIGNAL p118tmp_cast                     : signed(16 DOWNTO 0);  -- sfix17
  SIGNAL p118tmp_mul_temp                 : signed(48 DOWNTO 0);  -- sfix49_En30
  SIGNAL p118tmp_add_cast                 : signed(47 DOWNTO 0);  -- sfix48_En30
  SIGNAL p118tmp_add_cast_1               : signed(48 DOWNTO 0);  -- sfix49_En30
  SIGNAL p118tmp_cast_1                   : signed(16 DOWNTO 0);  -- sfix17
  SIGNAL p118tmp_mul_temp_1               : signed(48 DOWNTO 0);  -- sfix49_En30
  SIGNAL p118tmp_add_cast_2               : signed(47 DOWNTO 0);  -- sfix48_En30
  SIGNAL p118tmp_add_cast_3               : signed(48 DOWNTO 0);  -- sfix49_En30
  SIGNAL tmp_33                           : signed(48 DOWNTO 0);  -- sfix49_En30
  SIGNAL tmp_34                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL p159tmp_sub_cast                 : signed(31 DOWNTO 0);  -- int32
  SIGNAL sum1_re                          : vector_of_signed32(0 TO 262143);  -- sfix32_En9 [262144]
  SIGNAL sum1_im                          : vector_of_signed32(0 TO 262143);  -- sfix32_En9 [262144]
  SIGNAL tmp_re_25                        : signed(31 DOWNTO 0);  -- sfix32_En9
  SIGNAL tmp_im_25                        : signed(31 DOWNTO 0);  -- sfix32_En9
  SIGNAL p158tmp_sub_cast                 : signed(31 DOWNTO 0);  -- int32
  SIGNAL p158tmp_sub_cast_1               : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_re_26                        : signed(31 DOWNTO 0);  -- sfix32_En9
  SIGNAL tmp_im_26                        : signed(31 DOWNTO 0);  -- sfix32_En9
  SIGNAL tmp_re_27                        : signed(31 DOWNTO 0);  -- sfix32_En9
  SIGNAL tmp_im_27                        : signed(31 DOWNTO 0);  -- sfix32_En9
  SIGNAL p74tmp_add_cast                  : signed(53 DOWNTO 0);  -- sfix54_En30
  SIGNAL p74tmp_add_cast_1                : signed(53 DOWNTO 0);  -- sfix54_En30
  SIGNAL p74tmp_add_temp                  : signed(53 DOWNTO 0);  -- sfix54_En30
  SIGNAL p74tmp_add_cast_2                : signed(53 DOWNTO 0);  -- sfix54_En30
  SIGNAL p74tmp_add_cast_3                : signed(53 DOWNTO 0);  -- sfix54_En30
  SIGNAL p74tmp_add_temp_1                : signed(53 DOWNTO 0);  -- sfix54_En30
  SIGNAL sum1_re_1                        : vector_of_signed32(0 TO 262143);  -- sfix32_En9 [262144]
  SIGNAL sum1_im_1                        : vector_of_signed32(0 TO 262143);  -- sfix32_En9 [262144]
  SIGNAL tmp_re_28                        : vector_of_signed32(0 TO 262143);  -- sfix32_En9 [262144]
  SIGNAL tmp_im_28                        : vector_of_signed32(0 TO 262143);  -- sfix32_En9 [262144]
  SIGNAL sum1_re_2                        : vector_of_signed32(0 TO 262143);  -- sfix32_En9 [262144]
  SIGNAL sum1_im_2                        : vector_of_signed32(0 TO 262143);  -- sfix32_En9 [262144]
  SIGNAL tmp_re_29                        : vector_of_signed32(0 TO 262143);  -- sfix32_En9 [262144]
  SIGNAL tmp_im_29                        : vector_of_signed32(0 TO 262143);  -- sfix32_En9 [262144]
  SIGNAL tmp_re_30                        : vector_of_signed32(0 TO 262143);  -- sfix32_En9 [262144]
  SIGNAL tmp_im_30                        : vector_of_signed32(0 TO 262143);  -- sfix32_En9 [262144]
  SIGNAL tmp_re_31                        : vector_of_signed32(0 TO 262143);  -- sfix32_En9 [262144]
  SIGNAL tmp_im_31                        : vector_of_signed32(0 TO 262143);  -- sfix32_En9 [262144]
  SIGNAL csum1_re                         : signed(31 DOWNTO 0);  -- sfix32_En9
  SIGNAL csum1_im                         : signed(31 DOWNTO 0);  -- sfix32_En9
  SIGNAL p71csum1_sub_cast                : signed(31 DOWNTO 0);  -- int32
  SIGNAL p71csum1_sub_cast_1              : signed(31 DOWNTO 0);  -- int32
  SIGNAL ar_4                             : signed(31 DOWNTO 0);  -- sfix32_En9
  SIGNAL y_re_2                           : signed(31 DOWNTO 0);  -- sfix32_En24
  SIGNAL y_im_2                           : signed(31 DOWNTO 0);  -- sfix32_En24
  SIGNAL p101y_cast                       : signed(32 DOWNTO 0);  -- sfix33_En24
  SIGNAL p101y_cast_1                     : signed(32 DOWNTO 0);  -- sfix33_En24
  SIGNAL br_4                             : signed(31 DOWNTO 0);  -- sfix32_En24
  SIGNAL ai_4                             : signed(31 DOWNTO 0);  -- sfix32_En9
  SIGNAL bi_4                             : signed(31 DOWNTO 0);  -- sfix32_En24
  SIGNAL tmp_35                           : signed(31 DOWNTO 0);  -- sfix32_En4
  SIGNAL p61tmp_mul_temp                  : signed(63 DOWNTO 0);  -- sfix64_En33
  SIGNAL p61tmp_sub_cast                  : signed(64 DOWNTO 0);  -- sfix65_En33
  SIGNAL p61tmp_mul_temp_1                : signed(63 DOWNTO 0);  -- sfix64_En33
  SIGNAL p61tmp_sub_cast_1                : signed(64 DOWNTO 0);  -- sfix65_En33
  SIGNAL p61tmp_sub_temp                  : signed(64 DOWNTO 0);  -- sfix65_En33
  SIGNAL tmp_36                           : signed(31 DOWNTO 0);  -- sfix32_En4
  SIGNAL tmp_37                           : signed(31 DOWNTO 0);  -- sfix32_En4
  SIGNAL tmp_38                           : signed(31 DOWNTO 0);  -- sfix32_En4
  SIGNAL drift_SD_1                       : signed(31 DOWNTO 0);  -- sfix32_E11
  SIGNAL tmp_39                           : signed(31 DOWNTO 0);  -- sfix32_E11
  SIGNAL tmp_re_32                        : vector_of_signed32(0 TO 262143);  -- sfix32_E7 [262144]
  SIGNAL tmp_im_32                        : vector_of_signed32(0 TO 262143);  -- sfix32_E7 [262144]
  SIGNAL tmp_re_33                        : signed(31 DOWNTO 0);  -- sfix32_E7
  SIGNAL tmp_im_33                        : signed(31 DOWNTO 0);  -- sfix32_E7
  SIGNAL tmp_40                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL p172tmp_sub_cast                 : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_re_34                        : signed(31 DOWNTO 0);  -- sfix32_E7
  SIGNAL tmp_im_34                        : signed(31 DOWNTO 0);  -- sfix32_E7
  SIGNAL pre_1                            : signed(65 DOWNTO 0);  -- sfix66_En30
  SIGNAL ar_5                             : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL c_re_1                           : signed(32 DOWNTO 0);  -- sfix33
  SIGNAL c_im_1                           : signed(32 DOWNTO 0);  -- sfix33
  SIGNAL p162c_cast                       : signed(16 DOWNTO 0);  -- sfix17
  SIGNAL p162c_cast_1                     : signed(17 DOWNTO 0);  -- sfix18
  SIGNAL p162c_cast_2                     : signed(16 DOWNTO 0);  -- sfix17
  SIGNAL p162c_cast_3                     : signed(16 DOWNTO 0);  -- sfix17
  SIGNAL p162c_mul_temp                   : signed(33 DOWNTO 0);  -- sfix34
  SIGNAL br_5                             : signed(32 DOWNTO 0);  -- sfix33
  SIGNAL ai_5                             : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL bi_5                             : signed(32 DOWNTO 0);  -- sfix33
  SIGNAL tmp_41                           : signed(65 DOWNTO 0);  -- sfix66_En30
  SIGNAL p121tmp_mul_temp                 : signed(64 DOWNTO 0);  -- sfix65_En30
  SIGNAL p121tmp_sub_cast                 : signed(65 DOWNTO 0);  -- sfix66_En30
  SIGNAL p121tmp_mul_temp_1               : signed(64 DOWNTO 0);  -- sfix65_En30
  SIGNAL p121tmp_sub_cast_1               : signed(65 DOWNTO 0);  -- sfix66_En30
  SIGNAL tmp_42                           : signed(65 DOWNTO 0);  -- sfix66_En30
  SIGNAL pim_1                            : signed(65 DOWNTO 0);  -- sfix66_En30
  SIGNAL tmp_43                           : signed(65 DOWNTO 0);  -- sfix66_En30
  SIGNAL p122tmp_mul_temp                 : signed(64 DOWNTO 0);  -- sfix65_En30
  SIGNAL p122tmp_add_cast                 : signed(65 DOWNTO 0);  -- sfix66_En30
  SIGNAL p122tmp_mul_temp_1               : signed(64 DOWNTO 0);  -- sfix65_En30
  SIGNAL p122tmp_add_cast_1               : signed(65 DOWNTO 0);  -- sfix66_En30
  SIGNAL tmp_44                           : signed(65 DOWNTO 0);  -- sfix66_En30
  SIGNAL tmp_45                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL p164tmp_sub_cast                 : signed(31 DOWNTO 0);  -- int32
  SIGNAL sum2_re                          : vector_of_signed32(0 TO 262143);  -- sfix32_E7 [262144]
  SIGNAL sum2_im                          : vector_of_signed32(0 TO 262143);  -- sfix32_E7 [262144]
  SIGNAL tmp_re_35                        : signed(31 DOWNTO 0);  -- sfix32_E7
  SIGNAL tmp_im_35                        : signed(31 DOWNTO 0);  -- sfix32_E7
  SIGNAL p163tmp_sub_cast                 : signed(31 DOWNTO 0);  -- int32
  SIGNAL p163tmp_sub_cast_1               : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_re_36                        : signed(31 DOWNTO 0);  -- sfix32_E7
  SIGNAL tmp_im_36                        : signed(31 DOWNTO 0);  -- sfix32_E7
  SIGNAL tmp_re_37                        : signed(31 DOWNTO 0);  -- sfix32_E7
  SIGNAL tmp_im_37                        : signed(31 DOWNTO 0);  -- sfix32_E7
  SIGNAL p54tmp_add_cast                  : signed(69 DOWNTO 0);  -- sfix70_En30
  SIGNAL p54tmp_add_cast_1                : signed(69 DOWNTO 0);  -- sfix70_En30
  SIGNAL p54tmp_add_temp                  : signed(69 DOWNTO 0);  -- sfix70_En30
  SIGNAL p54tmp_add_cast_2                : signed(69 DOWNTO 0);  -- sfix70_En30
  SIGNAL p54tmp_add_cast_3                : signed(69 DOWNTO 0);  -- sfix70_En30
  SIGNAL p54tmp_add_temp_1                : signed(69 DOWNTO 0);  -- sfix70_En30
  SIGNAL sum2_re_1                        : vector_of_signed32(0 TO 262143);  -- sfix32_E7 [262144]
  SIGNAL sum2_im_1                        : vector_of_signed32(0 TO 262143);  -- sfix32_E7 [262144]
  SIGNAL tmp_re_38                        : vector_of_signed32(0 TO 262143);  -- sfix32_E7 [262144]
  SIGNAL tmp_im_38                        : vector_of_signed32(0 TO 262143);  -- sfix32_E7 [262144]
  SIGNAL sum2_re_2                        : vector_of_signed32(0 TO 262143);  -- sfix32_E7 [262144]
  SIGNAL sum2_im_2                        : vector_of_signed32(0 TO 262143);  -- sfix32_E7 [262144]
  SIGNAL tmp_re_39                        : vector_of_signed32(0 TO 262143);  -- sfix32_E7 [262144]
  SIGNAL tmp_im_39                        : vector_of_signed32(0 TO 262143);  -- sfix32_E7 [262144]
  SIGNAL tmp_re_40                        : vector_of_signed32(0 TO 262143);  -- sfix32_E7 [262144]
  SIGNAL tmp_im_40                        : vector_of_signed32(0 TO 262143);  -- sfix32_E7 [262144]
  SIGNAL tmp_re_41                        : vector_of_signed32(0 TO 262143);  -- sfix32_E7 [262144]
  SIGNAL tmp_im_41                        : vector_of_signed32(0 TO 262143);  -- sfix32_E7 [262144]
  SIGNAL csum2_re                         : signed(31 DOWNTO 0);  -- sfix32_E7
  SIGNAL csum2_im                         : signed(31 DOWNTO 0);  -- sfix32_E7
  SIGNAL p51csum2_sub_cast                : signed(31 DOWNTO 0);  -- int32
  SIGNAL p51csum2_sub_cast_1              : signed(31 DOWNTO 0);  -- int32
  SIGNAL ar_6                             : signed(31 DOWNTO 0);  -- sfix32_E7
  SIGNAL y_re_3                           : signed(31 DOWNTO 0);  -- sfix32_En24
  SIGNAL y_im_3                           : signed(31 DOWNTO 0);  -- sfix32_En24
  SIGNAL p104y_cast                       : signed(32 DOWNTO 0);  -- sfix33_En24
  SIGNAL p104y_cast_1                     : signed(32 DOWNTO 0);  -- sfix33_En24
  SIGNAL br_6                             : signed(31 DOWNTO 0);  -- sfix32_En24
  SIGNAL ai_6                             : signed(31 DOWNTO 0);  -- sfix32_E7
  SIGNAL bi_6                             : signed(31 DOWNTO 0);  -- sfix32_En24
  SIGNAL ar_7                             : signed(31 DOWNTO 0);  -- sfix32_En9
  SIGNAL y_re_4                           : signed(31 DOWNTO 0);  -- sfix32_En9
  SIGNAL y_im_4                           : signed(31 DOWNTO 0);  -- sfix32_En9
  SIGNAL p68y_cast                        : signed(32 DOWNTO 0);  -- sfix33_En9
  SIGNAL p68y_cast_1                      : signed(32 DOWNTO 0);  -- sfix33_En9
  SIGNAL br_7                             : signed(31 DOWNTO 0);  -- sfix32_En9
  SIGNAL ai_7                             : signed(31 DOWNTO 0);  -- sfix32_En9
  SIGNAL bi_7                             : signed(31 DOWNTO 0);  -- sfix32_En9
  SIGNAL pre_2                            : signed(64 DOWNTO 0);  -- sfix65_En18
  SIGNAL p64pre_mul_temp                  : signed(63 DOWNTO 0);  -- sfix64_En18
  SIGNAL p64pre_sub_cast                  : signed(64 DOWNTO 0);  -- sfix65_En18
  SIGNAL p64pre_mul_temp_1                : signed(63 DOWNTO 0);  -- sfix64_En18
  SIGNAL p64pre_sub_cast_1                : signed(64 DOWNTO 0);  -- sfix65_En18
  SIGNAL pim_2                            : signed(64 DOWNTO 0);  -- sfix65_En18
  SIGNAL p65pim_mul_temp                  : signed(63 DOWNTO 0);  -- sfix64_En18
  SIGNAL p65pim_add_cast                  : signed(64 DOWNTO 0);  -- sfix65_En18
  SIGNAL p65pim_mul_temp_1                : signed(63 DOWNTO 0);  -- sfix64_En18
  SIGNAL p65pim_add_cast_1                : signed(64 DOWNTO 0);  -- sfix65_En18
  SIGNAL tmp_46                           : signed(31 DOWNTO 0);  -- sfix32_E11
  SIGNAL p48tmp_mul_temp                  : signed(63 DOWNTO 0);  -- sfix64_En17
  SIGNAL p48tmp_sub_cast                  : signed(64 DOWNTO 0);  -- sfix65_En17
  SIGNAL p48tmp_mul_temp_1                : signed(63 DOWNTO 0);  -- sfix64_En17
  SIGNAL p48tmp_sub_cast_1                : signed(64 DOWNTO 0);  -- sfix65_En17
  SIGNAL p48tmp_sub_temp                  : signed(64 DOWNTO 0);  -- sfix65_En17
  SIGNAL p48tmp_add_cast                  : signed(66 DOWNTO 0);  -- sfix67_En18
  SIGNAL p48tmp_add_cast_1                : signed(66 DOWNTO 0);  -- sfix67_En18
  SIGNAL p48tmp_add_temp                  : signed(66 DOWNTO 0);  -- sfix67_En18
  SIGNAL tmp_47                           : signed(31 DOWNTO 0);  -- sfix32_E11
  SIGNAL tmp_48                           : signed(31 DOWNTO 0);  -- sfix32_E11
  SIGNAL tmp_49                           : signed(31 DOWNTO 0);  -- sfix32_E11

BEGIN
  -- 'cal_average_instance_C1_fixpt:21' outreal = fi(0, 1, 32, 24, fm);
  -- 
  -- 'cal_average_instance_C1_fixpt:20' outready = false;
  outreal_1 <= to_signed(0, 32);

  tmp <= to_signed(0, 32);

  -- HDL code generation from MATLAB function: cal_average_instance_C1_fixpt
  tmp_re <= (OTHERS => to_signed(0, 32));
  tmp_im <= (OTHERS => to_signed(0, 32));

  tmp_re_1 <= to_signed(0, 32);
  tmp_im_1 <= to_signed(0, 32);

  calbin_unsigned <= unsigned(calbin);

  -- 'cal_average_instance_C1_fixpt:38' csum0alt = fi(sum0alt(calbin), 1, 32, 30, fm);
  -- 
  -- 'cal_average_instance_C1_fixpt:39' sum0alt(calbin) = complex(0,0);
  p166tmp_sub_cast <= signed(resize(calbin_unsigned, 32));
  tmp_1 <= p166tmp_sub_cast - 1;

  enb <= clk_enable;

  tmp_re_2 <= to_signed(0, 32);
  tmp_im_2 <= to_signed(0, 32);

  real_in_signed <= signed(real_in);

  imag_in_signed <= signed(imag_in);

  -- 'cal_average_instance_C1_fixpt:68' c = complex( fi( re, NT ), fi( im, NT ) );
  -- 
  -- 'cal_average_instance_C1_fixpt:67' NT = fixed.aggregateType( re, im );
  -- 
  -- Choose wider type
  -- 
  -- 'cal_average_instance_C1_fixpt:65' if isfi( re ) && isfi( im )
  -- 
  -- 'cal_average_instance_C1_fixpt:64' im = varargin{ 2 };
  -- 
  -- 'cal_average_instance_C1_fixpt:63' re = varargin{ 1 };
  -- 
  -- 'cal_average_instance_C1_fixpt:62' if nargin==2
  -- 
  -- 'cal_average_instance_C1_fixpt:61' coder.inline( 'always' );
  -- 
  -- 'cal_average_instance_C1_fixpt:19' cplx_in = fi(complexx(real_in, imag_in), 1, 32, 30, fm);
  -- 
  -- 'cal_average_instance_C1_fixpt:12' if isempty(sum0)
  -- 
  -- 'cal_average_instance_C1_fixpt:8' fm = get_fimath();
  -- 
  -- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  -- 
  --                                                                          %
  -- 
  --          Generated by MATLAB 9.12 and Fixed-Point Designer 7.4           %
  -- 
  --                                                                          %
  -- 
  -- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  cplx_in_re <= real_in_signed;
  cplx_in_im <= imag_in_signed;

  ar <= cplx_in_re;

  phase_cor_re_signed <= signed(phase_cor_re);

  phase_cor_im_signed <= signed(phase_cor_im);

  br <= phase_cor_re_signed;

  ai <= cplx_in_im;

  -- 'cal_average_instance_C1_fixpt:30' sum0(calbin) = sum0(calbin) + cplx_in;
  bi <= phase_cor_im_signed;

  -- HDL code generation from MATLAB function: cal_average_instance_C1_fixpt_trueregionp127
  p135tmp_mul_temp <= ar * br;
  p135tmp_sub_cast <= resize(p135tmp_mul_temp, 65);
  p135tmp_mul_temp_1 <= ai * bi;
  p135tmp_sub_cast_1 <= resize(p135tmp_mul_temp_1, 65);
  p135tmp_sub_temp <= p135tmp_sub_cast - p135tmp_sub_cast_1;
  tmp_re_3 <= p135tmp_sub_temp(61 DOWNTO 30);
  p135tmp_mul_temp_2 <= ar * bi;
  p135tmp_add_cast <= resize(p135tmp_mul_temp_2, 65);
  p135tmp_mul_temp_3 <= ai * br;
  p135tmp_add_cast_1 <= resize(p135tmp_mul_temp_3, 65);
  p135tmp_add_temp <= p135tmp_add_cast + p135tmp_add_cast_1;
  tmp_im_3 <= p135tmp_add_temp(61 DOWNTO 30);

  -- 'cal_average_instance_C1_fixpt:28' if readycal
  
  tmp_re_4 <= cplx_in_re WHEN readycal = '0' ELSE
      tmp_re_3;
  
  tmp_im_4 <= cplx_in_im WHEN readycal = '0' ELSE
      tmp_im_3;

  -- 'cal_average_instance_C1_fixpt:31' sum0alt(calbin) = sum0alt(calbin) + cplx_in*tick;
  p152tmp_sub_cast <= signed(resize(calbin_unsigned, 32));
  tmp_2 <= p152tmp_sub_cast - 1;

  -- HDL code generation from MATLAB function: cal_average_instance_C1_fixpt_trueregionp125
  p151tmp_sub_cast <= signed(resize(calbin_unsigned, 32));
  tmp_re_5 <= sum0_re(hdl_sim_index_check(to_integer(p151tmp_sub_cast - 1), 0, 262143));
  p151tmp_sub_cast_1 <= signed(resize(calbin_unsigned, 32));
  tmp_im_5 <= sum0_im(hdl_sim_index_check(to_integer(p151tmp_sub_cast_1 - 1), 0, 262143));

  
  tmp_re_6 <= tmp_re_2 WHEN readycal = '0' ELSE
      tmp_re_5;
  
  tmp_im_6 <= tmp_im_2 WHEN readycal = '0' ELSE
      tmp_im_5;

  p114tmp_add_cast <= resize(tmp_re_6 & '0' & '0' & '0' & '0' & '0' & '0', 39);
  p114tmp_add_cast_1 <= resize(tmp_re_4, 39);
  p114tmp_add_temp <= p114tmp_add_cast + p114tmp_add_cast_1;
  tmp_re_7 <= p114tmp_add_temp(37 DOWNTO 6);
  p114tmp_add_cast_2 <= resize(tmp_im_6 & '0' & '0' & '0' & '0' & '0' & '0', 39);
  p114tmp_add_cast_3 <= resize(tmp_im_4, 39);
  p114tmp_add_temp_1 <= p114tmp_add_cast_2 + p114tmp_add_cast_3;
  tmp_im_7 <= p114tmp_add_temp_1(37 DOWNTO 6);

  -- HDL code generation from MATLAB function: cal_average_instance_C1_fixpt_trueregionp112
  p0sum0_output : PROCESS (sum0_im, sum0_re, tmp_2, tmp_im_7, tmp_re_7)
  BEGIN
    sum0_re_1 <= sum0_re;
    sum0_im_1 <= sum0_im;
    sum0_re_1(hdl_sim_index_check(to_integer(tmp_2), 0, 262143)) <= tmp_re_7;
    sum0_im_1(hdl_sim_index_check(to_integer(tmp_2), 0, 262143)) <= tmp_im_7;
  END PROCESS p0sum0_output;


  -- HDL code generation from MATLAB function: cal_average_instance_C1_fixpt_trueregionp46_trueregionp1
  p0sum0_1_output : PROCESS (tmp_1, tmp_im_1, tmp_im_8, tmp_re_1, tmp_re_8)
  BEGIN
    sum0_re_2 <= tmp_re_8;
    sum0_im_2 <= tmp_im_8;
    sum0_re_2(hdl_sim_index_check(to_integer(tmp_1), 0, 262143)) <= tmp_re_1;
    sum0_im_2(hdl_sim_index_check(to_integer(tmp_1), 0, 262143)) <= tmp_im_1;
  END PROCESS p0sum0_1_output;


  -- HDL code generation from MATLAB function: cal_average_instance_C1_fixpt_trueregionp46
  
  tmp_re_9 <= tmp_re_8 WHEN readyout = '0' ELSE
      sum0_re_2;
  
  tmp_im_9 <= tmp_im_8 WHEN readyout = '0' ELSE
      sum0_im_2;

  -- HDL code generation from MATLAB function: cal_average_instance_C1_fixpt_trueregionp26
  
  tmp_re_10 <= tmp_re WHEN readycal = '0' ELSE
      tmp_re_9;
  
  tmp_im_10 <= tmp_im WHEN readycal = '0' ELSE
      tmp_im_9;

  
  tmp_re_11 <= tmp_re_8 WHEN readycal = '0' ELSE
      tmp_re_10;
  
  tmp_im_11 <= tmp_im_8 WHEN readycal = '0' ELSE
      tmp_im_10;

  sum0_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      sum0_re <= (OTHERS => to_signed(0, 32));
      sum0_im <= (OTHERS => to_signed(0, 32));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        sum0_re <= tmp_re_11;
        sum0_im <= tmp_im_11;
      END IF;
    END IF;
  END PROCESS sum0_reg_process;


  
  tmp_re_8 <= sum0_re WHEN readycal = '0' ELSE
      sum0_re_1;
  
  tmp_im_8 <= sum0_im WHEN readycal = '0' ELSE
      sum0_im_1;

  p111csum0_sub_cast <= signed(resize(calbin_unsigned, 32));
  csum0_re <= tmp_re_8(hdl_sim_index_check(to_integer(p111csum0_sub_cast - 1), 0, 262143));
  p111csum0_sub_cast_1 <= signed(resize(calbin_unsigned, 32));
  csum0_im <= tmp_im_8(hdl_sim_index_check(to_integer(p111csum0_sub_cast_1 - 1), 0, 262143));

  -- HDL code generation from MATLAB function: cal_average_instance_C1_fixpt_trueregionp38_trueregionp1
  tmp_3 <= csum0_re;

  -- HDL code generation from MATLAB function: cal_average_instance_C1_fixpt_trueregionp38
  
  tmp_4 <= outreal_1 WHEN readyout = '0' ELSE
      tmp_3;

  -- HDL code generation from MATLAB function: cal_average_instance_C1_fixpt_trueregionp14
  
  tmp_5 <= tmp WHEN readycal = '0' ELSE
      tmp_4;

  
  tmp_6 <= outreal_1 WHEN readycal = '0' ELSE
      tmp_5;

  outreal <= std_logic_vector(tmp_6);

  -- 'cal_average_instance_C1_fixpt:22' outimag = fi(0, 1, 32, 24, fm);
  outimag_1 <= to_signed(0, 32);

  tmp_7 <= to_signed(0, 32);

  -- HDL code generation from MATLAB function: cal_average_instance_C1_fixpt_trueregionp36_trueregionp1
  tmp_8 <= csum0_im;

  -- HDL code generation from MATLAB function: cal_average_instance_C1_fixpt_trueregionp36
  
  tmp_9 <= outimag_1 WHEN readyout = '0' ELSE
      tmp_8;

  -- HDL code generation from MATLAB function: cal_average_instance_C1_fixpt_trueregionp12
  
  tmp_10 <= tmp_7 WHEN readycal = '0' ELSE
      tmp_9;

  
  tmp_11 <= outimag_1 WHEN readycal = '0' ELSE
      tmp_10;

  outimag <= std_logic_vector(tmp_11);

  -- 'cal_average_instance_C1_fixpt:24' powertop = fi(0, 0, 32, 18, fm);
  -- 
  -- 'cal_average_instance_C1_fixpt:23' outbin = fi(0, 0, 1, 0, fm);
  powertop_1 <= to_unsigned(0, 32);

  tmp_12 <= to_unsigned(0, 32);

  ar_1 <= csum0_re;

  y_re <= csum0_re;
  p108y_cast <= resize(csum0_im, 33);
  p108y_cast_1 <=  - (p108y_cast);
  y_im <= p108y_cast_1(31 DOWNTO 0);

  br_1 <= y_re;

  ai_1 <= csum0_im;

  bi_1 <= y_im;

  -- HDL code generation from MATLAB function: cal_average_instance_C1_fixpt_trueregionp30_trueregionp1
  p105tmp_mul_temp <= ar_1 * br_1;
  p105tmp_sub_cast <= resize(p105tmp_mul_temp, 65);
  p105tmp_mul_temp_1 <= ai_1 * bi_1;
  p105tmp_sub_cast_1 <= resize(p105tmp_mul_temp_1, 65);
  p105tmp_sub_temp <= p105tmp_sub_cast - p105tmp_sub_cast_1;
  tmp_13 <= unsigned(p105tmp_sub_temp(61 DOWNTO 30));

  -- HDL code generation from MATLAB function: cal_average_instance_C1_fixpt_trueregionp30
  
  tmp_14 <= powertop_1 WHEN readyout = '0' ELSE
      tmp_13;

  -- HDL code generation from MATLAB function: cal_average_instance_C1_fixpt_trueregionp6
  
  tmp_15 <= tmp_12 WHEN readycal = '0' ELSE
      tmp_14;

  
  tmp_16 <= powertop_1 WHEN readycal = '0' ELSE
      tmp_15;

  powertop <= std_logic_vector(tmp_16);

  -- 'cal_average_instance_C1_fixpt:25' powerbot =fi(0, 0, 32, 30, fm);
  powerbot_1 <= to_unsigned(0, 32);

  tmp_17 <= to_unsigned(0, 32);

  tmp_re_12 <= (OTHERS => to_signed(0, 32));
  tmp_im_12 <= (OTHERS => to_signed(0, 32));

  tmp_re_13 <= to_signed(0, 32);
  tmp_im_13 <= to_signed(0, 32);

  -- 'cal_average_instance_C1_fixpt:41' csum1 = fi(sum1(calbin), 1, 32, 9, fm);
  -- 
  -- 'cal_average_instance_C1_fixpt:42' sum1(calbin) = complex(0,0);
  p168tmp_sub_cast <= signed(resize(calbin_unsigned, 32));
  tmp_18 <= p168tmp_sub_cast - 1;

  -- 'cal_average_instance_C1_fixpt:29' cplx_in(:) = cplx_in*phase_cor;
  tmp_re_14 <= to_signed(0, 32);
  tmp_im_14 <= to_signed(0, 32);

  cr <= to_signed(0, 34);

  tick_signed <= signed(tick);

  -- HDL code generation from MATLAB function: cal_average_instance_C1_fixpt_trueregionp95
  tmp_19 <= tmp_re_4 * tick_signed;

  
  tmp_20 <= cr WHEN readycal = '0' ELSE
      tmp_19;

  ci <= to_signed(0, 34);

  -- HDL code generation from MATLAB function: cal_average_instance_C1_fixpt_trueregionp93
  tmp_21 <= tmp_im_4 * tick_signed;

  
  tmp_22 <= ci WHEN readycal = '0' ELSE
      tmp_21;

  -- 'cal_average_instance_C1_fixpt:32' sum1(calbin) = sum1(calbin) + cplx_in*complexx(fi(0, 0, 1, 0, fm),kar);
  -- 
  -- 'cal_average_instance_C1_fixpt:61' coder.inline( 'always' );
  -- 
  -- 'cal_average_instance_C1_fixpt:62' if nargin==2
  -- 
  -- 'cal_average_instance_C1_fixpt:63' re = varargin{ 1 };
  -- 
  -- 'cal_average_instance_C1_fixpt:64' im = varargin{ 2 };
  -- 
  -- 'cal_average_instance_C1_fixpt:65' if isfi( re ) && isfi( im )
  -- 
  -- Choose wider type
  -- 
  -- 'cal_average_instance_C1_fixpt:67' NT = fixed.aggregateType( re, im );
  -- 
  -- 'cal_average_instance_C1_fixpt:68' c = complex( fi( re, NT ), fi( im, NT ) );
  p154tmp_sub_cast <= signed(resize(calbin_unsigned, 32));
  tmp_23 <= p154tmp_sub_cast - 1;

  -- HDL code generation from MATLAB function: cal_average_instance_C1_fixpt_trueregionp91
  p153tmp_sub_cast <= signed(resize(calbin_unsigned, 32));
  tmp_re_15 <= sum0alt_re(hdl_sim_index_check(to_integer(p153tmp_sub_cast - 1), 0, 262143));
  p153tmp_sub_cast_1 <= signed(resize(calbin_unsigned, 32));
  tmp_im_15 <= sum0alt_im(hdl_sim_index_check(to_integer(p153tmp_sub_cast_1 - 1), 0, 262143));

  
  tmp_re_16 <= tmp_re_14 WHEN readycal = '0' ELSE
      tmp_re_15;
  
  tmp_im_16 <= tmp_im_14 WHEN readycal = '0' ELSE
      tmp_im_15;

  p90tmp_add_cast <= resize(tmp_re_16, 35);
  p90tmp_add_cast_1 <= resize(tmp_20, 35);
  p90tmp_add_temp <= p90tmp_add_cast + p90tmp_add_cast_1;
  tmp_re_17 <= p90tmp_add_temp(31 DOWNTO 0);
  p90tmp_add_cast_2 <= resize(tmp_im_16, 35);
  p90tmp_add_cast_3 <= resize(tmp_22, 35);
  p90tmp_add_temp_1 <= p90tmp_add_cast_2 + p90tmp_add_cast_3;
  tmp_im_17 <= p90tmp_add_temp_1(31 DOWNTO 0);

  -- HDL code generation from MATLAB function: cal_average_instance_C1_fixpt_trueregionp88
  p0sum0alt_output : PROCESS (sum0alt_im, sum0alt_re, tmp_23, tmp_im_17, tmp_re_17)
  BEGIN
    sum0alt_re_1 <= sum0alt_re;
    sum0alt_im_1 <= sum0alt_im;
    sum0alt_re_1(hdl_sim_index_check(to_integer(tmp_23), 0, 262143)) <= tmp_re_17;
    sum0alt_im_1(hdl_sim_index_check(to_integer(tmp_23), 0, 262143)) <= tmp_im_17;
  END PROCESS p0sum0alt_output;


  -- HDL code generation from MATLAB function: cal_average_instance_C1_fixpt_trueregionp44_trueregionp1
  p0sum0alt_1_output : PROCESS (tmp_18, tmp_im_13, tmp_im_18, tmp_re_13, tmp_re_18)
  BEGIN
    sum0alt_re_2 <= tmp_re_18;
    sum0alt_im_2 <= tmp_im_18;
    sum0alt_re_2(hdl_sim_index_check(to_integer(tmp_18), 0, 262143)) <= tmp_re_13;
    sum0alt_im_2(hdl_sim_index_check(to_integer(tmp_18), 0, 262143)) <= tmp_im_13;
  END PROCESS p0sum0alt_1_output;


  -- HDL code generation from MATLAB function: cal_average_instance_C1_fixpt_trueregionp44
  
  tmp_re_19 <= tmp_re_18 WHEN readyout = '0' ELSE
      sum0alt_re_2;
  
  tmp_im_19 <= tmp_im_18 WHEN readyout = '0' ELSE
      sum0alt_im_2;

  -- HDL code generation from MATLAB function: cal_average_instance_C1_fixpt_trueregionp23
  
  tmp_re_20 <= tmp_re_12 WHEN readycal = '0' ELSE
      tmp_re_19;
  
  tmp_im_20 <= tmp_im_12 WHEN readycal = '0' ELSE
      tmp_im_19;

  
  tmp_re_21 <= tmp_re_18 WHEN readycal = '0' ELSE
      tmp_re_20;
  
  tmp_im_21 <= tmp_im_18 WHEN readycal = '0' ELSE
      tmp_im_20;

  sum0alt_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      sum0alt_re <= (OTHERS => to_signed(0, 32));
      sum0alt_im <= (OTHERS => to_signed(0, 32));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        sum0alt_re <= tmp_re_21;
        sum0alt_im <= tmp_im_21;
      END IF;
    END IF;
  END PROCESS sum0alt_reg_process;


  
  tmp_re_18 <= sum0alt_re WHEN readycal = '0' ELSE
      sum0alt_re_1;
  
  tmp_im_18 <= sum0alt_im WHEN readycal = '0' ELSE
      sum0alt_im_1;

  p87csum0alt_sub_cast <= signed(resize(calbin_unsigned, 32));
  csum0alt_re <= tmp_re_18(hdl_sim_index_check(to_integer(p87csum0alt_sub_cast - 1), 0, 262143));
  p87csum0alt_sub_cast_1 <= signed(resize(calbin_unsigned, 32));
  csum0alt_im <= tmp_im_18(hdl_sim_index_check(to_integer(p87csum0alt_sub_cast_1 - 1), 0, 262143));

  ar_2 <= csum0alt_re;

  y_re_1 <= csum0alt_re;
  p84y_cast <= resize(csum0alt_im, 33);
  p84y_cast_1 <=  - (p84y_cast);
  y_im_1 <= p84y_cast_1(31 DOWNTO 0);

  br_2 <= y_re_1;

  ai_2 <= csum0alt_im;

  bi_2 <= y_im_1;

  -- HDL code generation from MATLAB function: cal_average_instance_C1_fixpt_trueregionp28_trueregionp1
  p81tmp_mul_temp <= ar_2 * br_2;
  p81tmp_sub_cast <= resize(p81tmp_mul_temp, 65);
  p81tmp_mul_temp_1 <= ai_2 * bi_2;
  p81tmp_sub_cast_1 <= resize(p81tmp_mul_temp_1, 65);
  p81tmp_sub_temp <= p81tmp_sub_cast - p81tmp_sub_cast_1;
  tmp_24 <= unsigned(p81tmp_sub_temp(61 DOWNTO 30));

  -- HDL code generation from MATLAB function: cal_average_instance_C1_fixpt_trueregionp28
  
  tmp_25 <= powerbot_1 WHEN readyout = '0' ELSE
      tmp_24;

  -- HDL code generation from MATLAB function: cal_average_instance_C1_fixpt_trueregionp4
  
  tmp_26 <= tmp_17 WHEN readycal = '0' ELSE
      tmp_25;

  
  tmp_27 <= powerbot_1 WHEN readycal = '0' ELSE
      tmp_26;

  powerbot <= std_logic_vector(tmp_27);

  -- 'cal_average_instance_C1_fixpt:26' drift_FD = fi(0, 1, 32, 4, fm);
  drift_FD_1 <= to_signed(0, 32);

  tmp_28 <= to_signed(0, 32);

  tmp_re_22 <= (OTHERS => to_signed(0, 32));
  tmp_im_22 <= (OTHERS => to_signed(0, 32));

  tmp_re_23 <= to_signed(0, 32);
  tmp_im_23 <= to_signed(0, 32);

  -- 'cal_average_instance_C1_fixpt:43' csum2 = fi(sum2(calbin), 1, 32, -7, fm);
  -- 
  -- 'cal_average_instance_C1_fixpt:44' sum2(calbin) = complex(0,0);
  p170tmp_sub_cast <= signed(resize(calbin_unsigned, 32));
  tmp_29 <= p170tmp_sub_cast - 1;

  tmp_re_24 <= to_signed(0, 32);
  tmp_im_24 <= to_signed(0, 32);

  pre <= to_signed(0, 49);

  ar_3 <= tmp_re_4;

  kar_unsigned <= unsigned(kar);

  c_re <= to_unsigned(16#0000#, 16);
  c_im <= kar_unsigned;

  br_3 <= c_re;

  ai_3 <= tmp_im_4;

  bi_3 <= c_im;

  -- HDL code generation from MATLAB function: cal_average_instance_C1_fixpt_trueregionp79
  p117tmp_cast <= signed(resize(br_3, 17));
  p117tmp_mul_temp <= ar_3 * p117tmp_cast;
  p117tmp_sub_cast <= p117tmp_mul_temp(47 DOWNTO 0);
  p117tmp_sub_cast_1 <= resize(p117tmp_sub_cast, 49);
  p117tmp_cast_1 <= signed(resize(bi_3, 17));
  p117tmp_mul_temp_1 <= ai_3 * p117tmp_cast_1;
  p117tmp_sub_cast_2 <= p117tmp_mul_temp_1(47 DOWNTO 0);
  p117tmp_sub_cast_3 <= resize(p117tmp_sub_cast_2, 49);
  tmp_30 <= p117tmp_sub_cast_1 - p117tmp_sub_cast_3;

  
  tmp_31 <= pre WHEN readycal = '0' ELSE
      tmp_30;

  pim <= to_signed(0, 49);

  -- HDL code generation from MATLAB function: cal_average_instance_C1_fixpt_trueregionp77
  p118tmp_cast <= signed(resize(bi_3, 17));
  p118tmp_mul_temp <= ar_3 * p118tmp_cast;
  p118tmp_add_cast <= p118tmp_mul_temp(47 DOWNTO 0);
  p118tmp_add_cast_1 <= resize(p118tmp_add_cast, 49);
  p118tmp_cast_1 <= signed(resize(br_3, 17));
  p118tmp_mul_temp_1 <= ai_3 * p118tmp_cast_1;
  p118tmp_add_cast_2 <= p118tmp_mul_temp_1(47 DOWNTO 0);
  p118tmp_add_cast_3 <= resize(p118tmp_add_cast_2, 49);
  tmp_32 <= p118tmp_add_cast_1 + p118tmp_add_cast_3;

  
  tmp_33 <= pim WHEN readycal = '0' ELSE
      tmp_32;

  -- 'cal_average_instance_C1_fixpt:33' sum2(calbin) = sum2(calbin) + cplx_in*complexx(fi_uminus(kar)*kar,fi(0, 0, 1, 
  -- 0, fm))
  -- 
  -- 'cal_average_instance_C1_fixpt:79' coder.inline( 'always' );
  -- 
  -- 'cal_average_instance_C1_fixpt:80' if isfi( a )
  -- 
  -- 'cal_average_instance_C1_fixpt:81' nt = numerictype( a );
  -- 
  -- 'cal_average_instance_C1_fixpt:82' new_nt = numerictype( 1, nt.WordLength + 1, nt.FractionLength );
  -- 
  -- 'cal_average_instance_C1_fixpt:83' y = -fi( a, new_nt, fimath( a ) );
  -- 
  -- 'cal_average_instance_C1_fixpt:61' coder.inline( 'always' );
  -- 
  -- 'cal_average_instance_C1_fixpt:62' if nargin==2
  -- 
  -- 'cal_average_instance_C1_fixpt:63' re = varargin{ 1 };
  -- 
  -- 'cal_average_instance_C1_fixpt:64' im = varargin{ 2 };
  -- 
  -- 'cal_average_instance_C1_fixpt:65' if isfi( re ) && isfi( im )
  -- 
  -- Choose wider type
  -- 
  -- 'cal_average_instance_C1_fixpt:67' NT = fixed.aggregateType( re, im );
  -- 
  -- 'cal_average_instance_C1_fixpt:68' c = complex( fi( re, NT ), fi( im, NT ) );
  p159tmp_sub_cast <= signed(resize(calbin_unsigned, 32));
  tmp_34 <= p159tmp_sub_cast - 1;

  -- HDL code generation from MATLAB function: cal_average_instance_C1_fixpt_trueregionp75
  p158tmp_sub_cast <= signed(resize(calbin_unsigned, 32));
  tmp_re_25 <= sum1_re(hdl_sim_index_check(to_integer(p158tmp_sub_cast - 1), 0, 262143));
  p158tmp_sub_cast_1 <= signed(resize(calbin_unsigned, 32));
  tmp_im_25 <= sum1_im(hdl_sim_index_check(to_integer(p158tmp_sub_cast_1 - 1), 0, 262143));

  
  tmp_re_26 <= tmp_re_24 WHEN readycal = '0' ELSE
      tmp_re_25;
  
  tmp_im_26 <= tmp_im_24 WHEN readycal = '0' ELSE
      tmp_im_25;

  p74tmp_add_cast <= resize(tmp_re_26 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 54);
  p74tmp_add_cast_1 <= resize(tmp_31, 54);
  p74tmp_add_temp <= p74tmp_add_cast + p74tmp_add_cast_1;
  tmp_re_27 <= p74tmp_add_temp(52 DOWNTO 21);
  p74tmp_add_cast_2 <= resize(tmp_im_26 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 54);
  p74tmp_add_cast_3 <= resize(tmp_33, 54);
  p74tmp_add_temp_1 <= p74tmp_add_cast_2 + p74tmp_add_cast_3;
  tmp_im_27 <= p74tmp_add_temp_1(52 DOWNTO 21);

  -- HDL code generation from MATLAB function: cal_average_instance_C1_fixpt_trueregionp72
  p0sum1_output : PROCESS (sum1_im, sum1_re, tmp_34, tmp_im_27, tmp_re_27)
  BEGIN
    sum1_re_1 <= sum1_re;
    sum1_im_1 <= sum1_im;
    sum1_re_1(hdl_sim_index_check(to_integer(tmp_34), 0, 262143)) <= tmp_re_27;
    sum1_im_1(hdl_sim_index_check(to_integer(tmp_34), 0, 262143)) <= tmp_im_27;
  END PROCESS p0sum1_output;


  -- HDL code generation from MATLAB function: cal_average_instance_C1_fixpt_trueregionp42_trueregionp1
  p0sum1_1_output : PROCESS (tmp_29, tmp_im_23, tmp_im_28, tmp_re_23, tmp_re_28)
  BEGIN
    sum1_re_2 <= tmp_re_28;
    sum1_im_2 <= tmp_im_28;
    sum1_re_2(hdl_sim_index_check(to_integer(tmp_29), 0, 262143)) <= tmp_re_23;
    sum1_im_2(hdl_sim_index_check(to_integer(tmp_29), 0, 262143)) <= tmp_im_23;
  END PROCESS p0sum1_1_output;


  -- HDL code generation from MATLAB function: cal_average_instance_C1_fixpt_trueregionp42
  
  tmp_re_29 <= tmp_re_28 WHEN readyout = '0' ELSE
      sum1_re_2;
  
  tmp_im_29 <= tmp_im_28 WHEN readyout = '0' ELSE
      sum1_im_2;

  -- HDL code generation from MATLAB function: cal_average_instance_C1_fixpt_trueregionp20
  
  tmp_re_30 <= tmp_re_22 WHEN readycal = '0' ELSE
      tmp_re_29;
  
  tmp_im_30 <= tmp_im_22 WHEN readycal = '0' ELSE
      tmp_im_29;

  
  tmp_re_31 <= tmp_re_28 WHEN readycal = '0' ELSE
      tmp_re_30;
  
  tmp_im_31 <= tmp_im_28 WHEN readycal = '0' ELSE
      tmp_im_30;

  sum1_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      sum1_re <= (OTHERS => to_signed(0, 32));
      sum1_im <= (OTHERS => to_signed(0, 32));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        sum1_re <= tmp_re_31;
        sum1_im <= tmp_im_31;
      END IF;
    END IF;
  END PROCESS sum1_reg_process;


  
  tmp_re_28 <= sum1_re WHEN readycal = '0' ELSE
      sum1_re_1;
  
  tmp_im_28 <= sum1_im WHEN readycal = '0' ELSE
      sum1_im_1;

  p71csum1_sub_cast <= signed(resize(calbin_unsigned, 32));
  csum1_re <= tmp_re_28(hdl_sim_index_check(to_integer(p71csum1_sub_cast - 1), 0, 262143));
  p71csum1_sub_cast_1 <= signed(resize(calbin_unsigned, 32));
  csum1_im <= tmp_im_28(hdl_sim_index_check(to_integer(p71csum1_sub_cast_1 - 1), 0, 262143));

  ar_4 <= csum1_re;

  y_re_2 <= csum0_re;
  p101y_cast <= resize(csum0_im, 33);
  p101y_cast_1 <=  - (p101y_cast);
  y_im_2 <= p101y_cast_1(31 DOWNTO 0);

  br_4 <= y_re_2;

  ai_4 <= csum1_im;

  bi_4 <= y_im_2;

  -- HDL code generation from MATLAB function: cal_average_instance_C1_fixpt_trueregionp34_trueregionp1
  p61tmp_mul_temp <= ar_4 * br_4;
  p61tmp_sub_cast <= resize(p61tmp_mul_temp, 65);
  p61tmp_mul_temp_1 <= ai_4 * bi_4;
  p61tmp_sub_cast_1 <= resize(p61tmp_mul_temp_1, 65);
  p61tmp_sub_temp <= p61tmp_sub_cast - p61tmp_sub_cast_1;
  tmp_35 <= p61tmp_sub_temp(60 DOWNTO 29);

  -- HDL code generation from MATLAB function: cal_average_instance_C1_fixpt_trueregionp34
  
  tmp_36 <= drift_FD_1 WHEN readyout = '0' ELSE
      tmp_35;

  -- HDL code generation from MATLAB function: cal_average_instance_C1_fixpt_trueregionp10
  
  tmp_37 <= tmp_28 WHEN readycal = '0' ELSE
      tmp_36;

  
  tmp_38 <= drift_FD_1 WHEN readycal = '0' ELSE
      tmp_37;

  drift_FD <= std_logic_vector(tmp_38);

  -- 'cal_average_instance_C1_fixpt:27' drift_SD = fi(0, 1, 32, -11, fm);
  drift_SD_1 <= to_signed(0, 32);

  tmp_39 <= to_signed(0, 32);

  tmp_re_32 <= (OTHERS => to_signed(0, 32));
  tmp_im_32 <= (OTHERS => to_signed(0, 32));

  tmp_re_33 <= to_signed(0, 32);
  tmp_im_33 <= to_signed(0, 32);

  -- 'cal_average_instance_C1_fixpt:46' outreal(:) = real(csum0);
  -- 
  -- 'cal_average_instance_C1_fixpt:47' outimag(:) = imag(csum0);
  -- 
  -- 'cal_average_instance_C1_fixpt:48' drift_FD(:) = real(csum1*conj(csum0));
  -- 
  -- 'cal_average_instance_C1_fixpt:49' drift_SD(:) = real(csum2*conj(csum0) + csum1*conj(csum1));
  -- 
  -- 'cal_average_instance_C1_fixpt:51' powertop(:) = real(csum0*conj(csum0));
  -- 
  -- 'cal_average_instance_C1_fixpt:52' powerbot(:) = real(csum0alt*conj(csum0alt));
  p172tmp_sub_cast <= signed(resize(calbin_unsigned, 32));
  tmp_40 <= p172tmp_sub_cast - 1;

  tmp_re_34 <= to_signed(0, 32);
  tmp_im_34 <= to_signed(0, 32);

  pre_1 <= to_signed(0, 66);

  ar_5 <= tmp_re_4;

  p162c_cast <= signed(resize(kar_unsigned, 17));
  p162c_cast_1 <=  - (resize(p162c_cast, 18));
  p162c_cast_2 <= p162c_cast_1(16 DOWNTO 0);
  p162c_cast_3 <= signed(resize(kar_unsigned, 17));
  p162c_mul_temp <= p162c_cast_2 * p162c_cast_3;
  c_re_1 <= p162c_mul_temp(32 DOWNTO 0);
  c_im_1 <= to_signed(0, 33);

  br_5 <= c_re_1;

  ai_5 <= tmp_im_4;

  bi_5 <= c_im_1;

  -- HDL code generation from MATLAB function: cal_average_instance_C1_fixpt_trueregionp59
  p121tmp_mul_temp <= ar_5 * br_5;
  p121tmp_sub_cast <= resize(p121tmp_mul_temp, 66);
  p121tmp_mul_temp_1 <= ai_5 * bi_5;
  p121tmp_sub_cast_1 <= resize(p121tmp_mul_temp_1, 66);
  tmp_41 <= p121tmp_sub_cast - p121tmp_sub_cast_1;

  
  tmp_42 <= pre_1 WHEN readycal = '0' ELSE
      tmp_41;

  pim_1 <= to_signed(0, 66);

  -- HDL code generation from MATLAB function: cal_average_instance_C1_fixpt_trueregionp57
  p122tmp_mul_temp <= ar_5 * bi_5;
  p122tmp_add_cast <= resize(p122tmp_mul_temp, 66);
  p122tmp_mul_temp_1 <= ai_5 * br_5;
  p122tmp_add_cast_1 <= resize(p122tmp_mul_temp_1, 66);
  tmp_43 <= p122tmp_add_cast + p122tmp_add_cast_1;

  
  tmp_44 <= pim_1 WHEN readycal = '0' ELSE
      tmp_43;

  -- 'cal_average_instance_C1_fixpt:34' if (readyout)
  -- 
  -- 'cal_average_instance_C1_fixpt:36' csum0 = fi(sum0(calbin), 1, 32, 24, fm);
  -- 
  -- 'cal_average_instance_C1_fixpt:37' sum0(calbin) = complex(0,0);
  p164tmp_sub_cast <= signed(resize(calbin_unsigned, 32));
  tmp_45 <= p164tmp_sub_cast - 1;

  -- HDL code generation from MATLAB function: cal_average_instance_C1_fixpt_trueregionp55
  p163tmp_sub_cast <= signed(resize(calbin_unsigned, 32));
  tmp_re_35 <= sum2_re(hdl_sim_index_check(to_integer(p163tmp_sub_cast - 1), 0, 262143));
  p163tmp_sub_cast_1 <= signed(resize(calbin_unsigned, 32));
  tmp_im_35 <= sum2_im(hdl_sim_index_check(to_integer(p163tmp_sub_cast_1 - 1), 0, 262143));

  
  tmp_re_36 <= tmp_re_34 WHEN readycal = '0' ELSE
      tmp_re_35;
  
  tmp_im_36 <= tmp_im_34 WHEN readycal = '0' ELSE
      tmp_im_35;

  p54tmp_add_cast <= resize(tmp_re_36 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 70);
  p54tmp_add_cast_1 <= resize(tmp_42, 70);
  p54tmp_add_temp <= p54tmp_add_cast + p54tmp_add_cast_1;
  tmp_re_37 <= p54tmp_add_temp(68 DOWNTO 37);
  p54tmp_add_cast_2 <= resize(tmp_im_36 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 70);
  p54tmp_add_cast_3 <= resize(tmp_44, 70);
  p54tmp_add_temp_1 <= p54tmp_add_cast_2 + p54tmp_add_cast_3;
  tmp_im_37 <= p54tmp_add_temp_1(68 DOWNTO 37);

  -- HDL code generation from MATLAB function: cal_average_instance_C1_fixpt_trueregionp52
  p0sum2_output : PROCESS (sum2_im, sum2_re, tmp_45, tmp_im_37, tmp_re_37)
  BEGIN
    sum2_re_1 <= sum2_re;
    sum2_im_1 <= sum2_im;
    sum2_re_1(hdl_sim_index_check(to_integer(tmp_45), 0, 262143)) <= tmp_re_37;
    sum2_im_1(hdl_sim_index_check(to_integer(tmp_45), 0, 262143)) <= tmp_im_37;
  END PROCESS p0sum2_output;


  -- HDL code generation from MATLAB function: cal_average_instance_C1_fixpt_trueregionp40_trueregionp1
  p0sum2_1_output : PROCESS (tmp_40, tmp_im_33, tmp_im_38, tmp_re_33, tmp_re_38)
  BEGIN
    sum2_re_2 <= tmp_re_38;
    sum2_im_2 <= tmp_im_38;
    sum2_re_2(hdl_sim_index_check(to_integer(tmp_40), 0, 262143)) <= tmp_re_33;
    sum2_im_2(hdl_sim_index_check(to_integer(tmp_40), 0, 262143)) <= tmp_im_33;
  END PROCESS p0sum2_1_output;


  -- HDL code generation from MATLAB function: cal_average_instance_C1_fixpt_trueregionp40
  
  tmp_re_39 <= tmp_re_38 WHEN readyout = '0' ELSE
      sum2_re_2;
  
  tmp_im_39 <= tmp_im_38 WHEN readyout = '0' ELSE
      sum2_im_2;

  -- HDL code generation from MATLAB function: cal_average_instance_C1_fixpt_trueregionp17
  
  tmp_re_40 <= tmp_re_32 WHEN readycal = '0' ELSE
      tmp_re_39;
  
  tmp_im_40 <= tmp_im_32 WHEN readycal = '0' ELSE
      tmp_im_39;

  
  tmp_re_41 <= tmp_re_38 WHEN readycal = '0' ELSE
      tmp_re_40;
  
  tmp_im_41 <= tmp_im_38 WHEN readycal = '0' ELSE
      tmp_im_40;

  sum2_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      sum2_re <= (OTHERS => to_signed(0, 32));
      sum2_im <= (OTHERS => to_signed(0, 32));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        sum2_re <= tmp_re_41;
        sum2_im <= tmp_im_41;
      END IF;
    END IF;
  END PROCESS sum2_reg_process;


  
  tmp_re_38 <= sum2_re WHEN readycal = '0' ELSE
      sum2_re_1;
  
  tmp_im_38 <= sum2_im WHEN readycal = '0' ELSE
      sum2_im_1;

  p51csum2_sub_cast <= signed(resize(calbin_unsigned, 32));
  csum2_re <= tmp_re_38(hdl_sim_index_check(to_integer(p51csum2_sub_cast - 1), 0, 262143));
  p51csum2_sub_cast_1 <= signed(resize(calbin_unsigned, 32));
  csum2_im <= tmp_im_38(hdl_sim_index_check(to_integer(p51csum2_sub_cast_1 - 1), 0, 262143));

  ar_6 <= csum2_re;

  y_re_3 <= csum0_re;
  p104y_cast <= resize(csum0_im, 33);
  p104y_cast_1 <=  - (p104y_cast);
  y_im_3 <= p104y_cast_1(31 DOWNTO 0);

  br_6 <= y_re_3;

  ai_6 <= csum2_im;

  bi_6 <= y_im_3;

  ar_7 <= csum1_re;

  y_re_4 <= csum1_re;
  p68y_cast <= resize(csum1_im, 33);
  p68y_cast_1 <=  - (p68y_cast);
  y_im_4 <= p68y_cast_1(31 DOWNTO 0);

  br_7 <= y_re_4;

  ai_7 <= csum1_im;

  bi_7 <= y_im_4;

  p64pre_mul_temp <= ar_7 * br_7;
  p64pre_sub_cast <= resize(p64pre_mul_temp, 65);
  p64pre_mul_temp_1 <= ai_7 * bi_7;
  p64pre_sub_cast_1 <= resize(p64pre_mul_temp_1, 65);
  pre_2 <= p64pre_sub_cast - p64pre_sub_cast_1;

  p65pim_mul_temp <= ar_7 * bi_7;
  p65pim_add_cast <= resize(p65pim_mul_temp, 65);
  p65pim_mul_temp_1 <= ai_7 * br_7;
  p65pim_add_cast_1 <= resize(p65pim_mul_temp_1, 65);
  pim_2 <= p65pim_add_cast + p65pim_add_cast_1;

  -- HDL code generation from MATLAB function: cal_average_instance_C1_fixpt_trueregionp32_trueregionp1
  p48tmp_mul_temp <= ar_6 * br_6;
  p48tmp_sub_cast <= resize(p48tmp_mul_temp, 65);
  p48tmp_mul_temp_1 <= ai_6 * bi_6;
  p48tmp_sub_cast_1 <= resize(p48tmp_mul_temp_1, 65);
  p48tmp_sub_temp <= p48tmp_sub_cast - p48tmp_sub_cast_1;
  p48tmp_add_cast <= resize(p48tmp_sub_temp & '0', 67);
  p48tmp_add_cast_1 <= resize(pre_2, 67);
  p48tmp_add_temp <= p48tmp_add_cast + p48tmp_add_cast_1;
  tmp_46 <= p48tmp_add_temp(60 DOWNTO 29);

  -- HDL code generation from MATLAB function: cal_average_instance_C1_fixpt_trueregionp32
  
  tmp_47 <= drift_SD_1 WHEN readyout = '0' ELSE
      tmp_46;

  -- HDL code generation from MATLAB function: cal_average_instance_C1_fixpt_trueregionp8
  
  tmp_48 <= tmp_39 WHEN readycal = '0' ELSE
      tmp_47;

  
  tmp_49 <= drift_SD_1 WHEN readycal = '0' ELSE
      tmp_48;

  drift_SD <= std_logic_vector(tmp_49);

  ce_out <= clk_enable;

END rtl;

